name: jao
description: Just Another ORM for Dart. Because you didn't have enough options already.
version: 0.2.1
homepage: https://github.com/nexlabstudio/jao/tree/dev/packages/jao
repository: https://github.com/nexlabstudio/jao
issue_tracker: https://github.com/nexlabstudio/jao/issues

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  meta: ^1.9.0
  collection: ^1.17.0
  # Database drivers
  postgres: ^3.1.0
  mysql1: ^0.20.0
  sqlite3: ^3.1.1

dev_dependencies:
  coverage: ^1.15.0
  test: ^1.24.0
  lints: ^6.0.0
