name: jao_example
description: Dart Frog API demonstrating jao ORM with SQLite.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

# resolution: workspace

dependencies:
  dart_frog: ^1.2.0
  jao:
    git:
      url: https://github.com/nexlabstudio/jao.git
      ref: no-build-hooks
      path: packages/jao
  jao_cli: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.0
  jao_generator: ^0.2.1
  test: ^1.24.0
  lints: ^6.0.0
