# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 80%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

flags:
  unittests:
    paths:
      - packages/jao/lib/
      - packages/jao_cli/lib/
      - packages/jao_generator/lib/
    carryforward: true
