name: jao_cli
description: Command-line interface for jao ORM. Run migrations, generate schemas, and manage your database.
version: 0.0.1
homepage: https://github.com/nexlabstudio/jao/packages/jao_cli
repository: https://github.com/nexlabstudio/jao/packages/jao_cli
issue_tracker: https://github.com/nexlabstudio/jao/issues

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  jao:
    path: ../jao

dev_dependencies:
  coverage: ^1.15.0
  test: ^1.24.0
  lints: ^3.0.0

executables:
  jao: jao
